@ECHO OFF
pushd "%~dp0"

IF %PROCESSOR_ARCHITECTURE%==AMD64 SET ARCH=64bits
IF %PROCESSOR_ARCHITECTURE%==x86 SET ARCH=32bits
IF %PROCESSOR_ARCHITECTURE%==ARM64 SET ARCH=ARM64
IF DEFINED ARCH CALL :NEXT
EXIT

:NEXT
FOR %%F IN ("ESET Internet Security %ARCH%*.exe") DO SET "EXEFILE=%%~fF"
IF EXIST "%EXEFILE%" START "" "%EXEFILE%"
goto :EOF
